version: 2.1
orbs:
  linter: thekevjames/linter@1.1.15
jobs:
  build:
    parameters:
      perl-version:
        default: "latest"
        type: string
    docker:
      - image: perl:<< parameters.perl-version >>
    steps:
      - checkout

      - restore_cache:
          key: v3-perl_modules-<< parameters.perl-version >>-{{ checksum "cpanfile" }}
      - run:
          name: Installing CPAN dependencies
          command: cpanm --quiet --installdeps --notest .
      - save_cache:
          key: v3-perl_modules-<< parameters.perl-version >>-{{ checksum "cpanfile" }}
          paths:
            - /usr/local/lib/perl5/site_perl

      - run:
          name: Adding backuppc user
          command: useradd -s /usr/sbin/nologin backuppc
      - run:
          name: Building BackupPC distribution
          command: ./makeDist --version HEAD
      - run:
          name: Installing BackupPC
          command: |
            cd ./dist/BackupPC-HEAD
            ./configure.pl --batch
      - run:
          name: Starting BackupPC
          command: su -m -s /bin/sh backuppc -c '/usr/local/BackupPC/bin/BackupPC -d'
      - run:
          name: Checking BackupPC log
          command: >-
            cat /var/log/BackupPC/LOG;
            set +e;
            egrep -v '[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}(
            Reading hosts file|
            BackupPC HEAD \(Perl v5\.[0-9]{1,2}\.[0-9]\) started, pid [0-9]+|
            Next wakeup is [0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})$'
            /var/log/BackupPC/LOG; test $? -eq 1

  tidy:
    docker:
      - image: perl:latest
    steps:
      - run:
          name: Exporting env vars
          command: |
            cat >> $BASH_ENV \<<EOF
            export PATH=$PATH:$HOME/perl5/bin
            export PERL_CPANM_OPT=--local-lib=$HOME/perl5
            export PERL5LIB=$HOME/perl5/lib/perl5:$PERL5LIB
            EOF
      - checkout

      - restore_cache:
          key: v8-tidyall_dependencies
      - run:
          name: Installing CPAN dependencies
          command: |
            cpanm --quiet --notest \
              Code::TidyAll \
              Pod::Tidy
      - save_cache:
          key: v8-tidyall_dependencies
          paths:
            - ~/perl5

      - run:
          name: Running tidyall
          command: |
            tidyall --version
            tidyall -a --check-only
      - run:
          name: Tidiyng files
          command: tidyall -a
          when: on_fail
      - run:
          name: git diff
          # Exit status is forced to expand command output in job log
          command: tidyall -a && git --no-pager diff --color && false
          when: on_fail

workflows:
  build_and_tidy:
    jobs:
      - build:
          matrix:
            parameters:
              # Perl version matrix follows versions still in use by popular
              # distributions such as Debian or Ubuntu, see:
              # - https://www.cpan.org/src/
              # - https://packages.debian.org/search?keywords=perl
              # - https://packages.ubuntu.com/search?keywords=perl
              #
              # Available Docker images are listed here: https://hub.docker.com/_/perl
              perl-version: ["5.32", "5.30", "5.28", "5.26", "5.24", "5.22", "5.20"]
      - linter/pre-commit:
          pre-steps:
            - run:
                name: Force colored Git output
                command: git config --global color.ui always
      - tidy
